# -*- coding: utf-8 -*-
"""Emotion AI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ALQtDH_uXbYf1bGt1M2L9PEPfObYAUWq
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.python.keras import Sequential
from tensorflow.keras import layers, optimizers
from tensorflow.keras.applications import DenseNet121
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.initializers import glorot_uniform
from tensorflow.keras.utils import plot_model
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping, ModelCheckpoint, LearningRateScheduler
from IPython.display import display
from tensorflow.keras import backend as K
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

facialpoints_df = pd.read_csv('KeyFacialPoints.csv')

facialpoints_df

facialpoints_df.info()

facialpoints_df['Image'][1]

facialpoints_df.isnull().sum()

facialpoints_df.describe()

import copy
facialpoints_df_copy = copy.copy(facialpoints_df)

columns = facialpoints_df_copy.columns[:-1]
columns

facialpoints_df['Image'][0]

facialpoints_df_copy['Image'][0]

for i in range(len(columns)):
  if i%2 == 0:
    facialpoints_df_copy[columns[i]] = facialpoints_df_copy[columns[i]].apply(lambda x: 96. - float(x) )

facialpoints_df_augmented = np.concatenate((facialpoints_df,facialpoints_df_copy))

facialpoints_df_augmented.shape

y = facialpoints_df_augmented[:,:30]
y = np.asarray(y).astype(np.float32)
y.shape

checkpointer = ModelCheckpoint(filepath = "weights.hdf5", verbose = 1, save_best_only = True)